// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelAuction implements cancelAuction operation.
//
// Owner-only; allowed only before the first bid.
//
// POST /auctions/{id}/cancel
func (UnimplementedHandler) CancelAuction(ctx context.Context, params CancelAuctionParams) (r *Auction, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAuction implements createAuction operation.
//
// Create an auction.
//
// POST /auctions
func (UnimplementedHandler) CreateAuction(ctx context.Context, req *CreateAuctionRequest) (r *Auction, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuction implements getAuction operation.
//
// Get an auction by id.
//
// GET /auctions/{id}
func (UnimplementedHandler) GetAuction(ctx context.Context, params GetAuctionParams) (r *Auction, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAuctions implements listAuctions operation.
//
// Returns a paginated list of auctions.
//
// GET /auctions
func (UnimplementedHandler) ListAuctions(ctx context.Context, params ListAuctionsParams) (r *AuctionList, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginUser implements loginUser operation.
//
// Verifies credentials and returns a JWT.
//
// POST /auth/login
func (UnimplementedHandler) LoginUser(ctx context.Context, req *Credentials) (r *TokenResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkAuctionSold implements markAuctionSold operation.
//
// Owner-only; allowed only after the auction ended with a winner.
//
// POST /auctions/{id}/sold
func (UnimplementedHandler) MarkAuctionSold(ctx context.Context, params MarkAuctionSoldParams) (r *Auction, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements registerUser operation.
//
// Creates a user with a university email and password, returning a JWT.
//
// POST /auth/register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *Credentials) (r *TokenResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAuction implements updateAuction operation.
//
// Owner-only; allowed only before the first bid.
//
// PATCH /auctions/{id}
func (UnimplementedHandler) UpdateAuction(ctx context.Context, req *UpdateAuctionRequest, params UpdateAuctionParams) (r *Auction, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
