// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelAuctionOperation   OperationName = "CancelAuction"
	CreateAuctionOperation   OperationName = "CreateAuction"
	GetAuctionOperation      OperationName = "GetAuction"
	ListAuctionsOperation    OperationName = "ListAuctions"
	LoginUserOperation       OperationName = "LoginUser"
	MarkAuctionSoldOperation OperationName = "MarkAuctionSold"
	RegisterUserOperation    OperationName = "RegisterUser"
	UpdateAuctionOperation   OperationName = "UpdateAuction"
)
