// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelAuction implements cancelAuction operation.
	//
	// Owner-only; allowed only before the first bid.
	//
	// POST /auctions/{id}/cancel
	CancelAuction(ctx context.Context, params CancelAuctionParams) (*Auction, error)
	// CreateAuction implements createAuction operation.
	//
	// Create an auction.
	//
	// POST /auctions
	CreateAuction(ctx context.Context, req *CreateAuctionRequest) (*Auction, error)
	// GetAuction implements getAuction operation.
	//
	// Get an auction by id.
	//
	// GET /auctions/{id}
	GetAuction(ctx context.Context, params GetAuctionParams) (*Auction, error)
	// ListAuctions implements listAuctions operation.
	//
	// Returns a paginated list of auctions.
	//
	// GET /auctions
	ListAuctions(ctx context.Context, params ListAuctionsParams) (*AuctionList, error)
	// LoginUser implements loginUser operation.
	//
	// Verifies credentials and returns a JWT.
	//
	// POST /auth/login
	LoginUser(ctx context.Context, req *Credentials) (*TokenResponse, error)
	// MarkAuctionSold implements markAuctionSold operation.
	//
	// Owner-only; allowed only after the auction ended with a winner.
	//
	// POST /auctions/{id}/sold
	MarkAuctionSold(ctx context.Context, params MarkAuctionSoldParams) (*Auction, error)
	// RegisterUser implements registerUser operation.
	//
	// Creates a user with a university email and password, returning a JWT.
	//
	// POST /auth/register
	RegisterUser(ctx context.Context, req *Credentials) (*TokenResponse, error)
	// UpdateAuction implements updateAuction operation.
	//
	// Owner-only; allowed only before the first bid.
	//
	// PATCH /auctions/{id}
	UpdateAuction(ctx context.Context, req *UpdateAuctionRequest, params UpdateAuctionParams) (*Auction, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
