// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Auction
type Auction struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Owner       int64        `json:"owner"`
	StartPrice  int64        `json:"startPrice"`
	Step        int64        `json:"step"`
	BuyNowPrice OptInt64     `json:"buyNowPrice"`
	EndDate     time.Time    `json:"endDate"`
	State       AuctionState `json:"state"`
	Winner      OptInt64     `json:"winner"`
	// Highest bid so far, or the start price if there are no bids.
	CurrentPrice int64 `json:"currentPrice"`
	BidCount     int32 `json:"bidCount"`
}

// GetID returns the value of ID.
func (s *Auction) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Auction) GetName() string {
	return s.Name
}

// GetOwner returns the value of Owner.
func (s *Auction) GetOwner() int64 {
	return s.Owner
}

// GetStartPrice returns the value of StartPrice.
func (s *Auction) GetStartPrice() int64 {
	return s.StartPrice
}

// GetStep returns the value of Step.
func (s *Auction) GetStep() int64 {
	return s.Step
}

// GetBuyNowPrice returns the value of BuyNowPrice.
func (s *Auction) GetBuyNowPrice() OptInt64 {
	return s.BuyNowPrice
}

// GetEndDate returns the value of EndDate.
func (s *Auction) GetEndDate() time.Time {
	return s.EndDate
}

// GetState returns the value of State.
func (s *Auction) GetState() AuctionState {
	return s.State
}

// GetWinner returns the value of Winner.
func (s *Auction) GetWinner() OptInt64 {
	return s.Winner
}

// GetCurrentPrice returns the value of CurrentPrice.
func (s *Auction) GetCurrentPrice() int64 {
	return s.CurrentPrice
}

// GetBidCount returns the value of BidCount.
func (s *Auction) GetBidCount() int32 {
	return s.BidCount
}

// SetID sets the value of ID.
func (s *Auction) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Auction) SetName(val string) {
	s.Name = val
}

// SetOwner sets the value of Owner.
func (s *Auction) SetOwner(val int64) {
	s.Owner = val
}

// SetStartPrice sets the value of StartPrice.
func (s *Auction) SetStartPrice(val int64) {
	s.StartPrice = val
}

// SetStep sets the value of Step.
func (s *Auction) SetStep(val int64) {
	s.Step = val
}

// SetBuyNowPrice sets the value of BuyNowPrice.
func (s *Auction) SetBuyNowPrice(val OptInt64) {
	s.BuyNowPrice = val
}

// SetEndDate sets the value of EndDate.
func (s *Auction) SetEndDate(val time.Time) {
	s.EndDate = val
}

// SetState sets the value of State.
func (s *Auction) SetState(val AuctionState) {
	s.State = val
}

// SetWinner sets the value of Winner.
func (s *Auction) SetWinner(val OptInt64) {
	s.Winner = val
}

// SetCurrentPrice sets the value of CurrentPrice.
func (s *Auction) SetCurrentPrice(val int64) {
	s.CurrentPrice = val
}

// SetBidCount sets the value of BidCount.
func (s *Auction) SetBidCount(val int32) {
	s.BidCount = val
}

// Ref: #/components/schemas/AuctionList
type AuctionList struct {
	Items  []Auction `json:"items"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// GetItems returns the value of Items.
func (s *AuctionList) GetItems() []Auction {
	return s.Items
}

// GetLimit returns the value of Limit.
func (s *AuctionList) GetLimit() int32 {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *AuctionList) GetOffset() int32 {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *AuctionList) SetItems(val []Auction) {
	s.Items = val
}

// SetLimit sets the value of Limit.
func (s *AuctionList) SetLimit(val int32) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *AuctionList) SetOffset(val int32) {
	s.Offset = val
}

// Ref: #/components/schemas/AuctionState
type AuctionState string

const (
	AuctionStateACTIVE   AuctionState = "ACTIVE"
	AuctionStateENDED    AuctionState = "ENDED"
	AuctionStateSOLD     AuctionState = "SOLD"
	AuctionStateCANCELED AuctionState = "CANCELED"
)

// AllValues returns all AuctionState values.
func (AuctionState) AllValues() []AuctionState {
	return []AuctionState{
		AuctionStateACTIVE,
		AuctionStateENDED,
		AuctionStateSOLD,
		AuctionStateCANCELED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AuctionState) MarshalText() ([]byte, error) {
	switch s {
	case AuctionStateACTIVE:
		return []byte(s), nil
	case AuctionStateENDED:
		return []byte(s), nil
	case AuctionStateSOLD:
		return []byte(s), nil
	case AuctionStateCANCELED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AuctionState) UnmarshalText(data []byte) error {
	switch AuctionState(data) {
	case AuctionStateACTIVE:
		*s = AuctionStateACTIVE
		return nil
	case AuctionStateENDED:
		*s = AuctionStateENDED
		return nil
	case AuctionStateSOLD:
		*s = AuctionStateSOLD
		return nil
	case AuctionStateCANCELED:
		*s = AuctionStateCANCELED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreateAuctionRequest
type CreateAuctionRequest struct {
	Name        string    `json:"name"`
	StartPrice  int64     `json:"startPrice"`
	Step        int64     `json:"step"`
	BuyNowPrice OptInt64  `json:"buyNowPrice"`
	EndDate     time.Time `json:"endDate"`
}

// GetName returns the value of Name.
func (s *CreateAuctionRequest) GetName() string {
	return s.Name
}

// GetStartPrice returns the value of StartPrice.
func (s *CreateAuctionRequest) GetStartPrice() int64 {
	return s.StartPrice
}

// GetStep returns the value of Step.
func (s *CreateAuctionRequest) GetStep() int64 {
	return s.Step
}

// GetBuyNowPrice returns the value of BuyNowPrice.
func (s *CreateAuctionRequest) GetBuyNowPrice() OptInt64 {
	return s.BuyNowPrice
}

// GetEndDate returns the value of EndDate.
func (s *CreateAuctionRequest) GetEndDate() time.Time {
	return s.EndDate
}

// SetName sets the value of Name.
func (s *CreateAuctionRequest) SetName(val string) {
	s.Name = val
}

// SetStartPrice sets the value of StartPrice.
func (s *CreateAuctionRequest) SetStartPrice(val int64) {
	s.StartPrice = val
}

// SetStep sets the value of Step.
func (s *CreateAuctionRequest) SetStep(val int64) {
	s.Step = val
}

// SetBuyNowPrice sets the value of BuyNowPrice.
func (s *CreateAuctionRequest) SetBuyNowPrice(val OptInt64) {
	s.BuyNowPrice = val
}

// SetEndDate sets the value of EndDate.
func (s *CreateAuctionRequest) SetEndDate(val time.Time) {
	s.EndDate = val
}

// Ref: #/components/schemas/Credentials
type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *Credentials) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *Credentials) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *Credentials) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *Credentials) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/TokenResponse
type TokenResponse struct {
	// JWT to send as `Authorization: Bearer <token>`.
	Token string `json:"token"`
}

// GetToken returns the value of Token.
func (s *TokenResponse) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *TokenResponse) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/UpdateAuctionRequest
type UpdateAuctionRequest struct {
	Name        string    `json:"name"`
	StartPrice  int64     `json:"startPrice"`
	Step        int64     `json:"step"`
	BuyNowPrice OptInt64  `json:"buyNowPrice"`
	EndDate     time.Time `json:"endDate"`
}

// GetName returns the value of Name.
func (s *UpdateAuctionRequest) GetName() string {
	return s.Name
}

// GetStartPrice returns the value of StartPrice.
func (s *UpdateAuctionRequest) GetStartPrice() int64 {
	return s.StartPrice
}

// GetStep returns the value of Step.
func (s *UpdateAuctionRequest) GetStep() int64 {
	return s.Step
}

// GetBuyNowPrice returns the value of BuyNowPrice.
func (s *UpdateAuctionRequest) GetBuyNowPrice() OptInt64 {
	return s.BuyNowPrice
}

// GetEndDate returns the value of EndDate.
func (s *UpdateAuctionRequest) GetEndDate() time.Time {
	return s.EndDate
}

// SetName sets the value of Name.
func (s *UpdateAuctionRequest) SetName(val string) {
	s.Name = val
}

// SetStartPrice sets the value of StartPrice.
func (s *UpdateAuctionRequest) SetStartPrice(val int64) {
	s.StartPrice = val
}

// SetStep sets the value of Step.
func (s *UpdateAuctionRequest) SetStep(val int64) {
	s.Step = val
}

// SetBuyNowPrice sets the value of BuyNowPrice.
func (s *UpdateAuctionRequest) SetBuyNowPrice(val OptInt64) {
	s.BuyNowPrice = val
}

// SetEndDate sets the value of EndDate.
func (s *UpdateAuctionRequest) SetEndDate(val time.Time) {
	s.EndDate = val
}
